export const flexPcbCapabilitiesContent: Record<string, Record<string, string>> = {
	PCB: {
		"Overall size": "8x12 mm to 234x490 mm",
		"Minimum trace width / spacing": "0.08/0.08 mm (0.10/0.10 mm for 1 oz Cu)",
		"Through hole diameter": "0.20~6.50 mm (tolerance ±0.05 mm)",
		"Minimum slot width": "0.6mm",
		"Minimum annular ring": "0.1mm",
		"Copper to hole clearance": "0.2mm",
		"Soldermask expansion": "0.1mm(each side)",
		"Minimum solder bridge": "0.5 mm (any solder bridge narrower than this will be removed)",
		"Minimum text thickness & height": "0.1/0.7 mm",
		"Pad To Silkscreen": "≥0.15mm",
		"Quality control": "Fully AOI & flying probe tested",
		"FPC Outline": "Laser cut (tolerance ±0.1 mm; copper to edge ≥ 0.15 mm)",
	},
	"Single-sided Flex PCB": {
		"ENIG Thickness": '1μ" / 2μ"',
		"Silkscreen Thickness": "10um",
		"Polyimide Thickness (external)": "12.5 μm / 25 μm",
		"Adhesive Thickness": "15 μm / 25 μm",
		"Copper Thickness": "0.5 oz / 1 oz",
		"Polyimide Thickness (internal)": "25um",
		"Stiffener Thickness": "0.05~0.25 mm (Drawing required)",
		"EMI Shielding Thickness": "18um",
		"Total Thickness": "0.07/0.11 mm",
	},
	"Double-sided Flex PCB": {
		"ENIG Thickness": '1μ" / 2μ"',
		"Silkscreen Thickness": "10um",
		"Polyimide Thickness (external)": "12.5 μm / 25 μm",
		"Adhesive Thickness": "15 μm / 25 μm",
		"Copper Thickness": "0.33 oz / 0.5 oz / 1 oz",
		"Polyimide Thickness (internal)": "25um",
		"Stiffener Thickness": "0.05~0.25 mm (Drawing required)",
		"EMI Shielding Thickness": "18um",
		"Total Thickness": "0.11 / 0.12 / 0.20 mm",
	},
};
