export const pcbAssemblyCapabilitiesContent: Record<string, string> = {
	"Assembly Types": "Single & double sided placement (SMT/Thru-hole)",
	"PCB Layer": "1-10 layers",
	Thickness: "0.4mm - 2.0mm",
	Dimension: "Single PCB Size:70x70mm - 510x460mm | PCB Panel Size: 70x70mm - 250x250mm",
	"Order Volume": "10-1000",
	"Delivery Format": "Single PCB, Panel with V-cut",
	"Minimum Package": "0201",
	"Minimum IC Pin Spacing": "0.35mm",
	"Minimum BGA Spacing": "0.5mm",
	"Reflow temperature": "240+/-5 °C",
	AOI: "Yes",
	"Visual Inspection": "Yes",
	"X-Ray Inspection": "Yes",
};
