export const rigidPcbCapabilitiesContent: Record<string, Record<string, string>> = {
	PCB: {
		"Layer Count": "1-20 Layers",
		"Controlled Impedance": "4/6 layer, default layer stack-up",
		"Material Types": "FR-4, Aluminum, Copper core, Rogers",
		"Dielectric Constant": "4.5(double-sided PCB)",
		"Max. Dimension": "400x500mm",
		"Dimension Tolerance": "±0.1mm",
		"Board Thickness": "0.4 - 2.5 mm",
		"Thickness Tolerance( Thickness≥1.0mm)": "± 10%",
		"Finished Outer Layer Copper": "1 oz / 2 oz (35um / 70um)",
		"Finished Inner Layer Copper": "0.5 oz / 1 oz / 2 oz (17.5um / 35um / 70um)",
		"Surface Finish": "HASL (leaded / lead-free), ENIG, OSP (copper core boards only)",
	},
	"Drill/Hole Size": {
		"Drill Hole Size": "0.15mm - 6.30mm",
		"Drill Hole Size Tolerance": "+0.13/-0.08mm",
		"Blind/Buried Vias": "Not Supported",
		"Min. Via hole size/diameter": "0.15mm / 0.25mm",
		"PTH hole Size": "0.20mm - 6.35mm",
		"Pad Size": "Minimum 1.0mm",
		"Min. Non-plated holes": "0.50mm",
		"NPTH Size": "0.2mm",
		"Min. Plated Slots": "0.5mm",
		"Min. Non-Plated Slots": "1.0mm",
		"Min. Castellated Holes": "0.60mm",
		"Hole size Tolerance (Plated)": "+0.13mm/-0.08mm",
		"Hole size Tolerance (Non-Plated)": "±0.2mm",
		"Rectangle Hole/Slot": "Not Supported",
	},
	"Minimum Annular Ring": {
		"1oz Copper": "0.13mm (PTH: 0.3mm)",
		"2oz Copper": "0.2mm (PTH: 0.3mm)",
	},
	"Minimum Clearance": {
		"Hole to hole clearance(Different nets)": "0.5mm",
		"Via to Via clearance(Same nets)": "0.254mm",
		"Pad to Pad clearance(Pad without hole, Different nets)": "0.127mm",
		"Pad to Pad clearance(Pad with hole, Different nets)": "0.5mm",
		"Via to Track": "0.254mm",
		"PTH to Track": "0.33mm",
		"NPTH to Track": "0.254mm",
		"Pad to Track": "0.2mm",
	},
	"Minimum Trace Width/Spacing": {
		"1-2 Layers": "5mil (0.127mm)/5mil (0.127mm)",
		"4-6 Layers": "3.5mil (0.09mm)/3.5mil (0.09mm)",
		"2oz Copper weight": "8mil (0.2mm)/8mil (0.2mm)",
	},
	"Min. BGA Pad Dimensions": {
		"1-2 Layers": "0.25mm",
		"4-6 Layers": "0.25mm",
	},
	"Min. Distance between BGA Pads": {
		"1-2 Layers": "0.127mm",
		"4-6 Layers": "0.127mm",
	},
	Soldermask: {
		"Soldermask Expansion": "0.038mm",
		"Min. Solder bridge": "0.10mm",
		"Via Covering": "Epoxy Filled & Capped | Copper paste Filled&Capped",
		"Solder mask color": "Green, Red, Yellow, Blue, White, and Black.",
		"Solder mask dielectric constant": "3.8",
		"Solder mask ink thickness": "10-15um",
	},
	Legend: {
		"Minimum Line Width": "6 mil (0.153mm)",
		"Minimum text height": "40 mil (1.0mm)",
		"Character width to height ratio": "1:6",
		"Hollow-carved Character width to height ratio": "1:6",
		"Pad To Silkscreen": "0.15mm",
	},
	"Board Outlines": {
		"Trace to Outline(Routed)": "0.3mm",
		"Trace to V-cut line(V-Cut Panel)": "0.4mm",
		"Mouse Bites Panel": "0.3mm",
	},
	Panelization: {
		"Panelization without space": "0mm",
		"Panelization with space": "2mm",
		"Panelized Round board": "≥20mmx20mm",
		"Panelized castellated holes board": "Panelize with stamp holes and add tooling strips on four board edges",
		"Min. Width of Breakaway Tab": "4mm",
		"Min. Edge Rails": "3mm",
	},
};
